/*
 Sam Buriima
generated by Saburi Tools
 */
package com.saburi.adminpanel.entities;

import java.util.Objects;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import org.hibernate.envers.Audited;
import org.hibernate.envers.RelationTargetAuditMode;
import com.saburi.common.entities.DBEntity;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import com.saburi.common.utils.CommonEnums.LicenseTypes;
import javax.persistence.Enumerated;
import java.time.LocalDate;

@Entity
@Audited(targetAuditMode = RelationTargetAuditMode.NOT_AUDITED)
public class LicenseGenerator extends DBEntity {

    @Column(updatable = false)
    private int idHelper;
    @Id
    @NotNull(message = "The field: License No cannot be null")
    @Size(max = 20, message = "The field: License No size cannot be greater than 100")
    @Column(length = 100, updatable = false)
    private String licenseNo;
    @Size(max = 100, message = "The field: Details size cannot be greater than 100")
    @Column(length = 100)
    private String details;
    @Enumerated
    private LicenseTypes licenseType;
    private LocalDate startDate;
    private LocalDate endDate;
    private int userLimit;
    private int recordLimit;
    @Size(max = 100, message = "The field: Base Table size cannot be greater than 100")
    @Column(length = 100)
    private String baseTable;

    public LicenseGenerator() {
    }

    public LicenseGenerator(int idHelper, String licenseNo, String details, LicenseTypes licenseType, LocalDate startDate, LocalDate endDate, int userLimit, int recordLimit, String baseTable) {
        this.idHelper = idHelper;
        this.licenseNo = licenseNo;
        this.details = details;
        this.licenseType = licenseType;
        this.startDate = startDate;
        this.endDate = endDate;
        this.userLimit = userLimit;
        this.recordLimit = recordLimit;
        this.baseTable = baseTable;

    }

    public int getIdHelper() {
        return idHelper;
    }

    public void setIdHelper(int idHelper) {
        this.idHelper = idHelper;
    }

    public String getLicenseNo() {
        return licenseNo;
    }

    public void setLicenseNo(String licenseNo) {
        this.licenseNo = licenseNo;
    }

    public String getDetails() {
        return details;
    }

    public void setDetails(String details) {
        this.details = details;
    }

    public LicenseTypes getLicenseType() {
        return licenseType;
    }

    public void setLicenseType(LicenseTypes licenseType) {
        this.licenseType = licenseType;
    }

    public LocalDate getStartDate() {
        return startDate;
    }

    public void setStartDate(LocalDate startDate) {
        this.startDate = startDate;
    }

    public LocalDate getEndDate() {
        return endDate;
    }

    public void setEndDate(LocalDate endDate) {
        this.endDate = endDate;
    }

    public int getUserLimit() {
        return userLimit;
    }

    public void setUserLimit(int userLimit) {
        this.userLimit = userLimit;
    }

    public int getRecordLimit() {
        return recordLimit;
    }

    public void setRecordLimit(int recordLimit) {
        this.recordLimit = recordLimit;
    }

    public String getBaseTable() {
        return baseTable;
    }

    public void setBaseTable(String baseTable) {
        this.baseTable = baseTable;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof LicenseGenerator)) {
            return false;
        }

        LicenseGenerator licenseGenerator = (LicenseGenerator) o;

        return this.getId().equals(licenseGenerator.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(this.licenseNo);

    }

    @Override
    public Object getId() {
        return this.licenseNo;
    }

    @Override
    public String getDisplayKey() {
        return this.licenseNo;
    }

}
